name: nduthi
description: A bodanduthi ride hailing app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google: ^0.0.1
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  create: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  dark_color: "#272727"
  image: assets/images/bodanduthil.png
  image_dark: assets/images/bodanduthil.png


flutter:
  uses-material-design: true
